//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Tools.CommonTools.src.DirectroyAndFile {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class clsDirectory_Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal clsDirectory_Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Tools.CommonTools.src.DirectroyAndFile.clsDirectory.Stringtable", typeof(clsDirectory_Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner öffnen ähnelt.
        /// </summary>
        internal static string _0x0001c {
            get {
                return ResourceManager.GetString("0x0001c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; konnte nicht geöffnet und gelesen werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0001m {
            get {
                return ResourceManager.GetString("0x0001m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner öffnen ähnelt.
        /// </summary>
        internal static string _0x0002c {
            get {
                return ResourceManager.GetString("0x0002c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; existiert nicht.
        ///Möchten Sie ihn jetzt anlegen? ähnelt.
        /// </summary>
        internal static string _0x0002m {
            get {
                return ResourceManager.GetString("0x0002m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner löschen ähnelt.
        /// </summary>
        internal static string _0x0003c {
            get {
                return ResourceManager.GetString("0x0003c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; konnte nicht gelöscht werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0003m {
            get {
                return ResourceManager.GetString("0x0003m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner löschen ähnelt.
        /// </summary>
        internal static string _0x0004c {
            get {
                return ResourceManager.GetString("0x0004c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind Sie sich sicher das Sie den Ordner &quot;{0}&quot; unwiederruflich löschen möchten? ähnelt.
        /// </summary>
        internal static string _0x0004m {
            get {
                return ResourceManager.GetString("0x0004m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner erstellen ähnelt.
        /// </summary>
        internal static string _0x0005c {
            get {
                return ResourceManager.GetString("0x0005c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; konnte nicht erstellt werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0005m {
            get {
                return ResourceManager.GetString("0x0005m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner kopieren ähnelt.
        /// </summary>
        internal static string _0x0006c {
            get {
                return ResourceManager.GetString("0x0006c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Kopieren des Ordners &quot;{0}&quot; nach &quot;{1}&quot; ist ein Fehler aufgetreten.
        ///
        ///{2} ähnelt.
        /// </summary>
        internal static string _0x0006m {
            get {
                return ResourceManager.GetString("0x0006m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zugriff auf Ordner ähnelt.
        /// </summary>
        internal static string _0x0007c {
            get {
                return ResourceManager.GetString("0x0007c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Zugriff auf den Ordner &quot;{0}&quot; wurde verweigert.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0007m {
            get {
                return ResourceManager.GetString("0x0007m", resourceCulture);
            }
        }
    }
}
