//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Tools.CommonTools.src.DirectroyAndFile {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class clsFileAssociation_Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal clsFileAssociation_Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Tools.CommonTools.src.DirectroyAndFile.clsFileAssociation.Stringtable", typeof(clsFileAssociation_Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finden von Dateizuordnungen ähnelt.
        /// </summary>
        internal static string FindApplication_Exception_Caption {
            get {
                return ResourceManager.GetString("FindApplication_Exception_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Finden der Dateizuordnung von {0}
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string FindApplication_Exception_Message {
            get {
                return ResourceManager.GetString("FindApplication_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf die angegebene Datei konnte nicht zugegriffen werden. ähnelt.
        /// </summary>
        internal static string FindApplication_SE_ERR_ACCESSDENIED {
            get {
                return ResourceManager.GetString("FindApplication_SE_ERR_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Datei wude nicht gefunden. ähnelt.
        /// </summary>
        internal static string FindApplication_SE_ERR_FNF {
            get {
                return ResourceManager.GetString("FindApplication_SE_ERR_FNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angebene Datei ist mit keiner Anwendung verknüpft. ähnelt.
        /// </summary>
        internal static string FindApplication_SE_ERR_NOASSOC {
            get {
                return ResourceManager.GetString("FindApplication_SE_ERR_NOASSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dem System stehen nicht genug Ressourcen oder zu wenig Arbeitsspeicher zur Verfügung. ähnelt.
        /// </summary>
        internal static string FindApplication_SE_ERR_OOM {
            get {
                return ResourceManager.GetString("FindApplication_SE_ERR_OOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Pfad ist nicht gültig. ähnelt.
        /// </summary>
        internal static string FindApplication_SE_ERR_PNF {
            get {
                return ResourceManager.GetString("FindApplication_SE_ERR_PNF", resourceCulture);
            }
        }
    }
}
