//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Tools.CommonTools.src.DirectroyAndFile {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class clsFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal clsFile() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Tools.CommonTools.src.DirectroyAndFile.clsFile", typeof(clsFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei kopieren ähnelt.
        /// </summary>
        internal static string Copy_Exception_Caoption {
            get {
                return ResourceManager.GetString("Copy_Exception_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Kopieren der Datei &quot;{0}&quot; nach &quot;{1}&quot; ist ein Fehler aufgetreten.
        ///
        ///Fehler:
        ///{2} ähnelt.
        /// </summary>
        internal static string Copy_Exception_Message {
            get {
                return ResourceManager.GetString("Copy_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei kopieren ähnelt.
        /// </summary>
        internal static string Copy_Exists_Caption {
            get {
                return ResourceManager.GetString("Copy_Exists_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zieldatei &quot;{0}&quot; existiert bereits. Möchten Sie diese überschreiben? ähnelt.
        /// </summary>
        internal static string Copy_Exists_Message {
            get {
                return ResourceManager.GetString("Copy_Exists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei erstellen ähnelt.
        /// </summary>
        internal static string Create_Exception_Caoption {
            get {
                return ResourceManager.GetString("Create_Exception_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht erstellt werden.
        ///
        ///Fehler:
        ///{1} ähnelt.
        /// </summary>
        internal static string Create_Exception_Message {
            get {
                return ResourceManager.GetString("Create_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei löschen ähnelt.
        /// </summary>
        internal static string Delete_Confirm_Caoption {
            get {
                return ResourceManager.GetString("Delete_Confirm_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind Sie sich sicher das Sie die Datei &quot;{0}&quot; tatsächlich löschen möchten? ähnelt.
        /// </summary>
        internal static string Delete_Confirm_Message {
            get {
                return ResourceManager.GetString("Delete_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht gelöscht werden.
        ///
        ///Fehler:
        ///{1} ähnelt.
        /// </summary>
        internal static string Delete_Exception_Message {
            get {
                return ResourceManager.GetString("Delete_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei löschen ähnelt.
        /// </summary>
        internal static string Delete_Exceptionn_Caoption {
            get {
                return ResourceManager.GetString("Delete_Exceptionn_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht geöffnet und gelesen werden.
        ///
        ///Fehler:
        ///{1} ähnelt.
        /// </summary>
        internal static string OpenToString_Exception_Message {
            get {
                return ResourceManager.GetString("OpenToString_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen und lesen ähnelt.
        /// </summary>
        internal static string OpenToString_Exceptionn_Caoption {
            get {
                return ResourceManager.GetString("OpenToString_Exceptionn_Caoption", resourceCulture);
            }
        }
    }
}
