//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Tools.CommonTools.src.DirectroyAndFile {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resClsDirectory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resClsDirectory() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Tools.CommonTools.src.DirectroyAndFile.resClsDirectory", typeof(resClsDirectory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Zugriff auf den Ordner &quot;{0}&quot; wurde verweigert.
        ///
        ///Meldung:
        ///{1} ähnelt.
        /// </summary>
        internal static string CheckAccess_Exception_Message {
            get {
                return ResourceManager.GetString("CheckAccess_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zugriff auf Ordner ähnelt.
        /// </summary>
        internal static string CheckAccess_Exceptionn_Caoption {
            get {
                return ResourceManager.GetString("CheckAccess_Exceptionn_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Kopieren des Ordners &quot;{0}&quot; nach &quot;{1}&quot; ist ein Fehler aufgetreten.
        ///
        ///Fehler:
        ///{2} ähnelt.
        /// </summary>
        internal static string Copy_Exception_Message {
            get {
                return ResourceManager.GetString("Copy_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner kopieren ähnelt.
        /// </summary>
        internal static string Copy_Exceptionn_Caoption {
            get {
                return ResourceManager.GetString("Copy_Exceptionn_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner erstellen ähnelt.
        /// </summary>
        internal static string Create_Exception_Caoption {
            get {
                return ResourceManager.GetString("Create_Exception_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; konnte nicht erstellt werden.
        ///
        ///Fehler:
        ///{1} ähnelt.
        /// </summary>
        internal static string Create_Exception_Message {
            get {
                return ResourceManager.GetString("Create_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner löschen ähnelt.
        /// </summary>
        internal static string Delete_Confirm_Caoption {
            get {
                return ResourceManager.GetString("Delete_Confirm_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind Sie sich sicher das Sie den Ordner &quot;{0}&quot; tatsächlich löschen möchten? ähnelt.
        /// </summary>
        internal static string Delete_Confirm_Message {
            get {
                return ResourceManager.GetString("Delete_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; konnte nicht gelöscht werden.
        ///
        ///Fehler:
        ///{1} ähnelt.
        /// </summary>
        internal static string Delete_Exception_Message {
            get {
                return ResourceManager.GetString("Delete_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner löschen ähnelt.
        /// </summary>
        internal static string Delete_Exceptionn_Caoption {
            get {
                return ResourceManager.GetString("Delete_Exceptionn_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; existiert nicht.
        ///Möchten Sie ihn jetzt anlegen? ähnelt.
        /// </summary>
        internal static string Open_AskCreate_Message {
            get {
                return ResourceManager.GetString("Open_AskCreate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner &quot;{0}&quot; konnte nicht geöffnet und gelesen werden.
        ///
        ///Fehler:
        ///{1} ähnelt.
        /// </summary>
        internal static string Open_Exception_Message {
            get {
                return ResourceManager.GetString("Open_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner öffnen ähnelt.
        /// </summary>
        internal static string Open_Exceptionn_Caoption {
            get {
                return ResourceManager.GetString("Open_Exceptionn_Caoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner öffnen ähnelt.
        /// </summary>
        internal static string Open_ExceptionOpen_AskCreate_Caoption {
            get {
                return ResourceManager.GetString("Open_ExceptionOpen_AskCreate_Caoption", resourceCulture);
            }
        }
    }
}
